# Generated by Django 4.2 on 2023-04-27 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tow_trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size_box', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='spares',
        ),
        migrations.DeleteModel(
            name='Spares',
        ),
        migrations.AddField(
            model_name='car',
            name='garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tow_trucks.garage'),
        ),
    ]
