# Generated by Django 4.2 on 2023-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('doc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
