# Generated by Django 4.2 on 2023-04-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_last_name_alter_worker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='doc',
        ),
    ]
