# Generated by Django 4.2 on 2023-04-27 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_remove_worker_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(70)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='experience',
            field=models.CharField(choices=[('<5', 'Меньше 6 месяцев'), ('>5', 'От 6 месяцев до 1 года'), ('>1', 'От 1 года до 3'), ('>3', 'Больше 3х лет')], default='<5', max_length=2, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sex',
            field=models.CharField(choices=[('f', 'Женщина'), ('m', 'Мужчина')], default='m', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='telephone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Должность'),
        ),
    ]
